myconfig:
  batchfile: C:/Users/elix/workspace/anomalyDetection/src/main/resources/log_input/batch_log.json
  streamfile: C:/Users/elix/workspace/anomalyDetection/src/main/resources/log_input/stream_log.json
  historyfile: C:/Users/elix/workspace/anomalyDetection/src/main/resources/log_output/purchase_log.json
  configfile: C:/Users/elix/workspace/anomalyDetection/src/main/resources/log_input/config_data.json
  flaggedfile: C:/Users/elix/workspace/anomalyDetection/src/main/resources/log_output/flagged_purchases.json